### ISSUE TITLE
Use IDs from main, not chat 

### ISSUE THREAD

**Issue by Geobits** [TehFlaminTaco/TacosUserscripts#7]
According to chatter here: http://chat.stackexchange.com/transcript/message/37006179#37006179

...the teams are assigned based on chat id. I assumed this was a companion piece to the red/blue challenges on main, and that the teams would be the same as there (if this is incorrect, disregard).

However, the script uses the user's chat ID, not the ID from main, so uh, yeah...

**Comment by TehFlaminTaco** [comment]
Not possible/easy with how the script works, as a User's PPCG ID isn't necessarily accessible from the chat.
